#include "BpSendStream.h"
#include "BpSendStreamRunner.h"

#include "Logger.h"
#include "SignalHandler.h"
#include <boost/filesystem.hpp>
#include <boost/program_options.hpp>
#include <boost/lexical_cast.hpp>
#include "Uri.h"
#include <cstdlib>

static constexpr hdtn::Logger::SubProcess subprocess = hdtn::Logger::SubProcess::none;

void BpSendStreamRunner::MonitorExitKeypressThreadFunction() {
    LOG_INFO(subprocess) << "Keyboard Interrupt.. exiting";
    m_runningFromSigHandler = false; //do this first
}




BpSendStreamRunner::BpSendStreamRunner() {}
BpSendStreamRunner::~BpSendStreamRunner() {}


std::string BpSendStreamRunner::ReadSdpFile(const boost::filesystem::path sdpFilePath)
{
    std::string ffmpegCommand;

    while (!boost::filesystem::exists(sdpFilePath))
    {

    }
    // wait for file to be written to
    boost::this_thread::sleep_for(boost::chrono::milliseconds(10));

    boost::filesystem::load_string_file(sdpFilePath, ffmpegCommand);
    // std::cout << ffmpegCommand << std::endl;
    return ffmpegCommand;
}

bool BpSendStreamRunner::Run(int argc, const char* const argv[], volatile bool & running, bool useSignalHandler) {
    //scope to ensure clean exit before return 0
    {
        running = true;
        m_runningFromSigHandler = true;
        SignalHandler sigHandler(boost::bind(&BpSendStreamRunner::MonitorExitKeypressThreadFunction, this));
        uint32_t bundleRate;

        cbhe_eid_t myEid;
        cbhe_eid_t finalDestEid;
        uint64_t myCustodianServiceId;
        OutductsConfig_ptr outductsConfigPtr;
        InductsConfig_ptr inductsConfigPtr;
        bool custodyTransferUseAcs;
        bool forceDisableCustody;
        bool useBpVersion7;
        unsigned int bundleSendTimeoutSeconds;
        uint64_t bundleLifetimeMilliseconds;
        uint64_t bundlePriority;

        size_t maxIncomingUdpPacketSizeBytes;
        uint16_t incomingRtpStreamPort;
        size_t numCircularBufferVectors;
        uint32_t maxBundleSizeBytes;
        bool enableRtpConcatenation;
        boost::filesystem::path sdpFilePath;

        boost::program_options::options_description desc("Allowed options");
        try {
            desc.add_options()
                ("help", "Produce help message.")
                ("bundle-size", boost::program_options::value<uint32_t>()->default_value(100), "Bundle size bytes.")
                ("bundle-rate", boost::program_options::value<uint32_t>()->default_value(1500), "Bundle rate. (0=>as fast as possible)")
                ("my-uri-eid", boost::program_options::value<std::string>()->default_value("ipn:1.1"), "BpGen Source Node Id.")
                ("dest-uri-eid", boost::program_options::value<std::string>()->default_value("ipn:2.1"), "BpGen sends to this final destination Eid.")
                ("my-custodian-service-id", boost::program_options::value<uint64_t>()->default_value(0), "Custodian service ID is always 0.")
                ("outducts-config-file", boost::program_options::value<boost::filesystem::path>()->default_value(""), "Outducts Configuration File.")
                ("custody-transfer-inducts-config-file", boost::program_options::value<boost::filesystem::path>()->default_value(""), "Inducts Configuration File for custody transfer (use custody if present).")
                ("custody-transfer-use-acs", "Custody transfer should use Aggregate Custody Signals instead of RFC5050.")
                ("force-disable-custody", "Custody transfer turned off regardless of link bidirectionality.")
                ("use-bp-version-7", "Send bundles using bundle protocol version 7.")
                ("bundle-send-timeout-seconds", boost::program_options::value<unsigned int>()->default_value(3), "Max time to send a bundle and get acknowledgement.")
                ("bundle-lifetime-milliseconds", boost::program_options::value<uint64_t>()->default_value(1000000), "Bundle lifetime in milliseconds.")
                ("bundle-priority", boost::program_options::value<uint64_t>()->default_value(2), "Bundle priority. 0 = Bulk 1 = Normal 2 = Expedited")
                ("max-incoming-udp-packet-size-bytes", boost::program_options::value<size_t>()->default_value(2), "Max size of incoming UDP packets (from the RTP stream). Use in conjection with FFmpeg")
                ("incoming-rtp-stream-port", boost::program_options::value<uint16_t>()->default_value(50000), "Where incoming RTP stream is being delivered")
                ("num-circular-buffer-vectors", boost::program_options::value<size_t>()->default_value(50), "Number of circular buffer vector elements in the udp sink")
                ("enable-rtp-concatenation", boost::program_options::value<bool>()->default_value(true), "Enable concatenation of incoming RTP packets to reduce RTP overhead")
                ("sdp-filepath", boost::program_options::value<boost::filesystem::path>()->default_value(""), "Location of SDP file generated by FFmpeg");

            
                boost::program_options::variables_map vm;
                boost::program_options::store(boost::program_options::parse_command_line(argc, argv, desc, boost::program_options::command_line_style::unix_style | boost::program_options::command_line_style::case_insensitive), vm);
                boost::program_options::notify(vm);

                if (vm.count("help")) {
                        LOG_INFO(subprocess) << desc;
                        return false;
                }
                forceDisableCustody = (vm.count("force-disable-custody") != 0);
                useBpVersion7 = (vm.count("use-bp-version-7") != 0);

                const std::string myUriEid = vm["my-uri-eid"].as<std::string>();
                if (!Uri::ParseIpnUriString(myUriEid, myEid.nodeId, myEid.serviceId)) {
                    LOG_ERROR(subprocess) << "error: bad bpsink uri string: " << myUriEid;
                    return false;
                }

                const std::string myFinalDestUriEid = vm["dest-uri-eid"].as<std::string>();
                if (!Uri::ParseIpnUriString(myFinalDestUriEid, finalDestEid.nodeId, finalDestEid.serviceId)) {
                    LOG_ERROR(subprocess) << "error: bad bpsink uri string: " << myFinalDestUriEid;
                    return false;
                }

                const boost::filesystem::path outductsConfigFileName = vm["outducts-config-file"].as<boost::filesystem::path>();

                if (!outductsConfigFileName.empty()) {
                    outductsConfigPtr = OutductsConfig::CreateFromJsonFilePath(outductsConfigFileName);
                    if (!outductsConfigPtr) {
                        LOG_ERROR(subprocess) << "error loading outducts config file: " << outductsConfigFileName;
                        return false;
                    }
                    std::size_t numBpGenOutducts = outductsConfigPtr->m_outductElementConfigVector.size();
                    if (numBpGenOutducts != 1) {
                        LOG_ERROR(subprocess) << "number of BpSendStream outducts is not 1: got " << numBpGenOutducts;
                    }
                }
                else {
                    LOG_WARNING(subprocess) << "notice: BpSendStream has no outduct... bundle data will have to flow out through a bidirectional tcpcl induct";
                }

                //create induct for custody signals
                const boost::filesystem::path inductsConfigFileName = vm["custody-transfer-inducts-config-file"].as<boost::filesystem::path>();
                if (!inductsConfigFileName.empty()) {
                    inductsConfigPtr = InductsConfig::CreateFromJsonFilePath(inductsConfigFileName);
                    if (!inductsConfigPtr) {
                        LOG_ERROR(subprocess) << "error loading induct config file: " << inductsConfigFileName;
                        return false;
                    }
                    std::size_t numBpGenInducts = inductsConfigPtr->m_inductElementConfigVector.size();
                    if (numBpGenInducts != 1) {
                        LOG_ERROR(subprocess) << "number of bp gen inducts for custody signals is not 1: got " << numBpGenInducts;
                    }
                }
                custodyTransferUseAcs = (vm.count("custody-transfer-use-acs"));


                myCustodianServiceId = vm["my-custodian-service-id"].as<uint64_t>();
                bundleSendTimeoutSeconds = vm["bundle-send-timeout-seconds"].as<unsigned int>();

                bundlePriority = vm["bundle-priority"].as<uint64_t>();
                if (bundlePriority > 2) {
                    std::cerr << "Priority must be 0, 1, or 2." << std::endl;
                    return false;
                }

                bundleLifetimeMilliseconds = vm["bundle-lifetime-milliseconds"].as<uint64_t>();

                maxIncomingUdpPacketSizeBytes =  vm["max-incoming-udp-packet-size-bytes"].as<size_t>();
                incomingRtpStreamPort =  vm["incoming-rtp-stream-port"].as<uint16_t>();
                numCircularBufferVectors = vm["num-circular-buffer-vectors"].as<size_t>();
                maxBundleSizeBytes = vm["bundle-size"].as<uint32_t>();
                bundleRate = vm["bundle-rate"].as<uint32_t>();
                enableRtpConcatenation = vm["enable-rtp-concatenation"].as<bool>();
                sdpFilePath = vm["sdp-filepath"].as<boost::filesystem::path>();
        }
        catch (boost::bad_any_cast & e) {
                LOG_ERROR(subprocess) << "invalid data error: " << e.what();
                LOG_ERROR(subprocess) << desc;
                return false;
        }
        catch (std::exception& e) {
                LOG_ERROR(subprocess) << e.what();
                return false;
        }
        catch (...) {
                LOG_ERROR(subprocess) << "Exception of unknown type!";
                return false;
        }


        LOG_INFO(subprocess) << "starting..";

        std::string sdpFile; 
        if (sdpFilePath.size() > 0)
            sdpFile = ReadSdpFile(sdpFilePath);

        std::cout << sdpFile << std::endl;

        BpSendStream bpSendStream(maxIncomingUdpPacketSizeBytes, incomingRtpStreamPort, numCircularBufferVectors, maxBundleSizeBytes, enableRtpConcatenation, sdpFile);

        bpSendStream.Start(
            outductsConfigPtr,
            inductsConfigPtr,
            custodyTransferUseAcs,
            myEid,
            bundleRate,
            finalDestEid,
            myCustodianServiceId,
            bundleSendTimeoutSeconds,
            bundleLifetimeMilliseconds,
            bundlePriority,
            false,
            forceDisableCustody,
            useBpVersion7
        );


        LOG_INFO(subprocess) << "running";
            

        if (useSignalHandler) {
            sigHandler.Start(false);
        }

        LOG_INFO(subprocess) << "Up and running";
        while (running && m_runningFromSigHandler) {
            boost::this_thread::sleep(boost::posix_time::millisec(250));
            if (useSignalHandler) {
                sigHandler.PollOnce();
            }
        }

        LOG_INFO(subprocess)<< "Exiting cleanly..";
        bpSendStream.Stop();
        m_bundleCount = bpSendStream.m_bundleCount;
        m_outductFinalStats = bpSendStream.m_outductFinalStats;
    }
    LOG_INFO(subprocess)<< "Exited cleanly";
    return true;

}
